#!/usr/bin/env bash
# script to dig subdomain information

domain="$1"
subdomain="$2"

if [ -z "$domain" ]; then
  echo "Please specify a domain name"
  exit 1
fi

if [ -z "$subdomain" ]; then
  subdomains=(www lb-01 web-01 web-02)
else
  subdomains=("$subdomain")
fi

for sub in "${subdomains[@]}"; do
  record=$(dig +short "$sub.$domain" | head -1)
  if [ -z "$record" ]; then
    echo "Subdomain $sub.$domain not found"
  else
    record_type=$(dig +short "$sub.$domain" | awk '{print $1}')
    echo "The subdomain $sub is a $record_type record and points to $record"
  fi
done
