#!/usr/bin/env bash
# Install nginx
apt-get update
apt-get -y install nginx

# Configure nginx
echo "Holberton School" | sudo tee /usr/share/nginx/html/index.html

# Start nginx
sudo service nginx start
