#!/usr/bin/env bash
# Install nginx
apt-get update
apt-get -y install nginx

# Configure nginx
echo "Hello World!" | sudo tee /usr/share/nginx/html/index.html
echo "server {
        listen 80 default_server;
        listen [::]:80 default_server;

        root /var/www/html;
        index index.html;

        server_name _;

        location /redirect_me {
                return 301 http://www.example.com/;
        }
}" > /etc/nginx/sites-available/default

# Restart nginx
service nginx restart
