#!/usr/bin/env bash
# Install nginx
sudo apt-get update
sudo apt-get -y install nginx

# Configure nginx
echo "server {
        listen 80 default_server;
        listen [::]:80 default_server;

        root /var/www/html;
        index index.html;

        server_name _;

        location / {
                try_files $uri $uri/ =404;
        }

        location /redirect_me {
                return 301 http://www.google.com
        }

        error_page 404 /404_not_found.html;
        location = /404_not_found.html {
                internal;
        }

}" > /etc/nginx/sites-available/default

echo "Hello World!" | sudo tee /var/www/html/index.html

# Start nginx
sudo service nginx start
