#!/bin/bash

# Custom header to be added
custom_header="add_header X-Served-By \$hostname;"

# Nginx configuration file
nginx_config="/etc/nginx/sites-available/default"

# Check if the configuration file exists
if [ -f "$nginx_config" ]; then
    # Add the custom header after the server_name in the configuration file
    sed -i "/^ *server_name _;/a \ \ \ \ $custom_header" "$nginx_config"

    # Restart Nginx to apply the changes
    sudo service nginx restart
else
    echo "Nginx configuration file not found."
fi

