#!/usr/bin/env bash
# script to add custom header to nginx.conf

#install nginx 
sudo apt-get update
sudo apt-get -y install nginx

#configure nginx.conf
sed -i 's/add_header X-Served-By $hostname;/' /etc/nginx/nginx.conf

#restart the nginx service
sudo service nginx restart