#!/usr/bin/env bash
# Install HAProxy
sudo apt update
sudo apt install -y haproxy

# Backup the original HAProxy configuration file
sudo mv /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.backup

# Create a new HAProxy configuration file
sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<EOF
global
    log /dev/log local0
    log /dev/log local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log global
    mode http
    option httplog
    option dontlognull
    timeout connect 5000
    timeout client 50000
    timeout server 50000

frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server web-01 52.3.253.65:80 check
    server web-02 100.25.179.167:80 check
EOF

# Start HAProxy service to apply changes
sudo systemctl start haproxy

# Enable HAProxy service to start on boot
sudo systemctl enable haproxy

