#!/usr/bin/env bash
# Define the path to the Gunicorn executable
GUNICORN_PATH="/home/ubuntu/.local/bin/gunicorn"

# Define the path to the Gunicorn PID file
PID_FILE="/var/run/gunicorn.pid"

# Check if the PID file exists
if [ -f "$PID_FILE" ]; then
    # Send a HUP signal to the Gunicorn master process to gracefully reload
    "$GUNICORN_PATH" --reload "$(cat "$PID_FILE")"
    echo "Gunicorn reloaded gracefully."
else
    echo "Gunicorn is not running or PID file not found."
fi

